on: 
  repository_dispatch:
      types: [incident-report]

jobs:
  handle-report:
    runs-on: ubuntu-latest
    steps:
      - name: print incident report 
        run: echo " incident report "
        
