on:
  push:
    branches:
      - main
      - "release/**"

    path:
      - "src/**"
      - "docs/**"
      - "README.md"

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.3
      - name: run test
        run: npm test
